---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule

metadata:
  name: slack

spec:
  host: slack.statesman.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
