---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
    name: slack

spec:
    minAvailable: 1
    selector:
        matchLabels:
            app: statesman
            version: v1
            component: slack
