---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: slack-credentials
  namespace: statesman

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: slack
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /pilgrimage/statesman/slack/credentials
