---
kind: Service
apiVersion: v1

metadata:
  name: slack-v1

spec:
  type: ClusterIP
  selector:
    app: slack-receiver
    version: v1
  ports:
    - name: api
      port: 5000
      targetPort: api
      protocol: TCP
